update indentation

diff --git a/install-deadline b/install-deadline
--- a/install-deadline
+++ b/install-deadline
@@ -193,51 +193,51 @@ function download_deadline {
   local attempt_upload="true"
 
   if [[ ! -d "$(dirname $deadline_installers_tar)" ]]; then
-    log_info "Ensuring dir exists for installers."
-    mkdir -p  "$(dirname $deadline_installers_tar)"
+      log_info "Ensuring dir exists for installers."
+      mkdir -p  "$(dirname $deadline_installers_tar)"
   fi
 
   if [[ -f "$deadline_installers_tar" ]]; then
-    log_info "File already exists: $deadline_installers_tar"
+      log_info "File already exists: $deadline_installers_tar"
   else
-    # Prefer installation from Thinkbox S3 Bucket for visibility when a version is deprecated.
-    log_info "Get object with: aws s3api head-object --bucket thinkbox-installers --key ${deadline_installer_bucket_key}"
-    output=$(aws s3api head-object --bucket thinkbox-installers --key "${deadline_installer_bucket_key}") && exit_status=0 || exit_status=$?
-    if [[ $exit_status -eq 0 ]]; then
-      log_info "...Downloading Deadline (${deadline_installers_filename}) from: thinkbox-installers"
-      aws s3api get-object --bucket thinkbox-installers --key "${deadline_installer_bucket_key}" "${deadline_installers_tar}"
-    else
-      printf "\n\nWarning: The installer was not aquired from Thinkbox.  It may have become deprecated.  Other AWS Accounts will not be able to install this version.\n\n"
-      if [[ ! -z "$installers_bucket" ]]; then
-        log_info "...Downloading from: $installers_bucket"
-        aws s3api get-object --bucket $installers_bucket --key "$deadline_installers_filename" "${deadline_installers_tar}"
-        attempt_upload="false"
+      # Prefer installation from Thinkbox S3 Bucket for visibility when a version is deprecated.
+      log_info "Get object with: aws s3api head-object --bucket thinkbox-installers --key ${deadline_installer_bucket_key}"
+      output=$(aws s3api head-object --bucket thinkbox-installers --key "${deadline_installer_bucket_key}") && exit_status=0 || exit_status=$?
+      if [[ $exit_status -eq 0 ]]; then
+          log_info "...Downloading Deadline (${deadline_installers_filename}) from: thinkbox-installers"
+          aws s3api get-object --bucket thinkbox-installers --key "${deadline_installer_bucket_key}" "${deadline_installers_tar}"
+      else
+          printf "\n\nWarning: The installer was not aquired from Thinkbox.  It may have become deprecated.  Other AWS Accounts will not be able to install this version.\n\n"
+          if [[ ! -z "$installers_bucket" ]]; then
+              log_info "...Downloading from: $installers_bucket"
+              aws s3api get-object --bucket $installers_bucket --key "$deadline_installers_filename" "${deadline_installers_tar}"
+              attempt_upload="false"
+          fi
       fi
-    fi
   fi
 
   if [[ ! -f "$deadline_installers_tar" ]]; then
-    log_error "File not found locally after attempted download"
-    exit 1
-  else
+      log_error "File not found locally after attempted download"
+      exit 1
+  fi
 
   # If this doesn't exist in user bucket, upload it for reproducibility (incase the Thinkbox installer becomes unavailable).
   if [[ "$attempt_upload" == "true" && ! -z "$installers_bucket" ]]; then
-    log_info "...Querying if this file exists in $installers_bucket"
-    output=$(aws s3api head-object --bucket $installers_bucket --key "$deadline_installers_filename") && exit_status=0 || exit_status=$?
-    if [[ ! $exit_status -eq 0 ]]; then
-      log_info "Uploading the file to $installers_bucket $deadline_installers_filename"
-      aws s3api put-object --bucket $installers_bucket --key "$deadline_installers_filename" --body "${deadline_installers_tar}"
-    else
-      log_info "The bucket $installers_bucket already contains: $deadline_installers_filename"
-    fi
+      log_info "...Querying if this file exists in $installers_bucket"
+      output=$(aws s3api head-object --bucket $installers_bucket --key "$deadline_installers_filename") && exit_status=0 || exit_status=$?
+      if [[ ! $exit_status -eq 0 ]]; then
+          log_info "Uploading the file to $installers_bucket $deadline_installers_filename"
+          aws s3api put-object --bucket $installers_bucket --key "$deadline_installers_filename" --body "${deadline_installers_tar}"
+      else
+          log_info "The bucket $installers_bucket already contains: $deadline_installers_filename"
+      fi
   fi
 
   if [[ "$extract_installer" == "true" ]]; then
-    log_info "...Extract installler"
-    sudo mkdir -p $deadline_installer_dir
-    # Extract Installer
-    sudo tar -xvf $deadline_installers_tar -C $deadline_installer_dir
+      log_info "...Extract installler"
+      sudo mkdir -p $deadline_installer_dir
+      # Extract Installer
+      sudo tar -xvf $deadline_installers_tar -C $deadline_installer_dir
   fi
 
 }
